steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/dom-tree-scraper-simple", "-f", "Dockerfile.simple", "."]
images:
  - "gcr.io/$PROJECT_ID/dom-tree-scraper-simple"
